import '../styles/globals.css'
import '@rainbow-me/rainbowkit/styles.css'

import type { AppProps } from 'next/app'
import Head from 'next/head'

import Layout from '@/components/Layout'
import { Web3Provider } from '@/components/web3-provider'
import { Suspense } from 'react'
import Home from '@/pages'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>{'RealitySync'}</title>
        <meta content={'Generated by @rainbow-me/create-rainbowkit'} name={'description'} />
        <link href={'/images/Logo_0.png'} rel={'icon'} />
      </Head>
      <Web3Provider>
      <Suspense fallback={<Home />}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
        </Suspense>
      </Web3Provider>
    </>
  )
}

export default MyApp
