import type { NextPage } from 'next'
import Head from 'next/head'

import Layout from '@/components/Layout'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{'RealitySync'}</title>
        <meta content={'Generated by @rainbow-me/create-rainbowkit'} name={'description'} />
        <link href={'/images/Logo_0.png'} rel={'icon'} />
      </Head>
      <Layout>
        <div className={'text-black'}>{' a '}</div>
      </Layout>
    </div>
  )
}

export default Home
