[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_protocol = "7M5iD5J7hFHuk3UeP1ykrJK2VTK26Va638omgWbtUzMi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mitrofan.tw/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
